// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "校验用户名和密码，登录成功返回 JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "通过 JWT 获取当前登录用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户",
                "responses": {
                    "200": {
                        "description": "当前用户信息",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录或 token 失效",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "注册一个新的系统用户，用户名唯一，密码使用 bcrypt 加密保存",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "409": {
                        "description": "用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询当前登录用户的合同列表，支持按合同名称/编号、状态、客户名称筛选",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同"
                ],
                "summary": "合同列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量，默认 10，最大 100",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "合同名称或合同编号关键字",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "合同状态：0已导入 1已分享 2协作中 3已确认 4已完成 5已取消",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "客户名称",
                        "name": "customer_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页合同列表",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传 DOCX 文件创建合同，文件保存到阿里云 OSS，并自动生成 V1 合同版本",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同"
                ],
                "summary": "创建合同",
                "parameters": [
                    {
                        "type": "string",
                        "description": "合同名称",
                        "name": "contract_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "DOCX 文件，仅支持 .docx",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "合同备注",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "客户名称/公司名称",
                        "name": "customer_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "客户联系人",
                        "name": "customer_contact",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "客户联系电话",
                        "name": "customer_phone",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误或文件不合法",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户创建的合同详情，包含当前版本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同"
                ],
                "summary": "合同详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "合同详情",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/changes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询合同版本之间的变更记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同版本"
                ],
                "summary": "变更记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量，默认 20，最大 100",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页变更记录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "内部用户确认当前版本",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "确认"
                ],
                "summary": "内部用户确认合同",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确认成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/confirmations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查看合同的确认记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "确认"
                ],
                "summary": "查看确认记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确认记录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/download": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "下载当前版本渲染后的 DOCX，内置水印",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                ],
                "tags": [
                    "下载"
                ],
                "summary": "下载最终 DOCX",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DOCX 文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/share": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为合同生成外部协作者分享链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "创建分享链接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分享参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享链接",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/share/{shareId}/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使分享链接失效",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "失效分享链接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分享记录ID",
                        "name": "shareId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "已失效",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/versions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询合同版本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同版本"
                ],
                "summary": "版本列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量，默认 10，最大 100",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分页版本列表",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "提交编辑后的结构化文档，自动生成新版本并记录变更",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同版本"
                ],
                "summary": "保存新版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新版本内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.SaveVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "保存成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在或无权访问",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "422": {
                        "description": "文档对比失败",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/versions/{versionId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定历史版本的完整结构化内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "合同版本"
                ],
                "summary": "版本详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "合同ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "versionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "版本详情",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "合同不存在、无权访问或版本不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "返回 /api 分组下的服务健康状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "API 健康检查",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}": {
            "get": {
                "description": "外部用户通过 token 获取合同概要",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "获取分享概要",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分享概要",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "分享链接不存在或已失效",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/changes": {
            "get": {
                "description": "外部协作者查看变更记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部变更记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "变更记录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/confirm": {
            "post": {
                "description": "外部协作者确认当前版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "确认"
                ],
                "summary": "外部协作者确认合同",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确认成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/confirmations": {
            "get": {
                "description": "外部协作者查看确认记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "确认"
                ],
                "summary": "外部查看确认记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "确认记录",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/contract": {
            "get": {
                "description": "外部协作者获取合同当前版本内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部获取合同内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "合同内容",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "403": {
                        "description": "协作者不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/download": {
            "get": {
                "description": "外部协作者下载当前版本渲染后的 DOCX，内置水印",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                ],
                "tags": [
                    "下载"
                ],
                "summary": "外部下载最终 DOCX",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DOCX 文件",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/join": {
            "post": {
                "description": "外部用户输入姓名加入合同协作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部协作者加入",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "姓名",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.joinShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "协作者信息",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/versions": {
            "get": {
                "description": "外部协作者分页查看合同版本列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "版本列表",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "description": "外部协作者提交修改，生成新版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部保存版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "新版本内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.SaveVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "保存成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    },
                    "403": {
                        "description": "只读链接不可编辑",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/api/share/{token}/versions/{versionId}": {
            "get": {
                "description": "外部协作者查看指定版本详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分享协作"
                ],
                "summary": "外部版本详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分享Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "versionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "协作者姓名",
                        "name": "collaborator_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "版本详情",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "返回 Go 服务基础运行状态，供部署探活使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "服务健康检查",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github_com_lshc_contract-hub_backend_pkg_response.Body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_lshc_contract-hub_backend_pkg_response.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "登录密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "登录账号",
                    "type": "string",
                    "example": "zhangsan"
                }
            }
        },
        "internal_handler.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string",
                    "example": "zhangsan@example.com"
                },
                "nickname": {
                    "description": "昵称/姓名",
                    "type": "string",
                    "example": "张三"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string",
                    "example": "13800138000"
                },
                "username": {
                    "description": "登录账号",
                    "type": "string",
                    "example": "zhangsan"
                }
            }
        },
        "internal_handler.SaveVersionRequest": {
            "type": "object",
            "properties": {
                "change_summary": {
                    "type": "string"
                },
                "document_content": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "internal_handler.createShareRequest": {
            "type": "object",
            "properties": {
                "expire_hours": {
                    "type": "integer",
                    "example": 24
                },
                "permission": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_handler.joinShareRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "张三"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "心智协同合同协作系统 API",
	Description:      "心智协同合同协作系统 V1 后端接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
