-- V3.11 用户电子章库
CREATE TABLE IF NOT EXISTS user_seal_asset (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id BIGINT NOT NULL COMMENT '所属内部用户',
  name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '印章名称',
  oss_key VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'OSS Object Key',
  file_url VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '可访问 URL',
  mime_type VARCHAR(64) NOT NULL DEFAULT 'image/png' COMMENT 'MIME',
  file_size INT NOT NULL DEFAULT 0 COMMENT '字节数',
  width_px INT NOT NULL DEFAULT 0 COMMENT '宽（可选）',
  height_px INT NOT NULL DEFAULT 0 COMMENT '高（可选）',
  is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认章 0否1是',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0软删',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_user_seal_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户电子章库';
